Repository SE2-Projekt-WelcomeToTheMoon/server, pull requests merged in 2024-05, with the labels that each got.

#76 Adapted SendMessageService.java.
  src/main/java/WebsocketServer/services/SendMessageService.java
Labels: enhancement

#59 Add Data Structure for rockets
  src/main/java/WebsocketServer/game/model/GameBoard.java
  src/main/java/WebsocketServer/game/model/RocketBarometer.java
  src/test/java/WebsocketServer/game/model/GameBoardTest.java
  src/test/java/WebsocketServer/game/model/RocketBarometerTest.java
Labels: enhancement

#68 Implement Network Communication for GameBoard Data
  .idea/.gitignore
  src/main/java/WebsocketServer/game/enums/FieldCategory.java
  src/main/java/WebsocketServer/game/model/Chamber.java
  src/main/java/WebsocketServer/game/model/FieldUpdateMessage.java
  src/main/java/WebsocketServer/game/model/Floor.java
  src/main/java/WebsocketServer/game/model/GameBoard.java
  src/main/java/WebsocketServer/services/GameBoardManager.java
  src/main/java/WebsocketServer/services/user/CreateUserService.java
  src/test/java/WebsocketServer/game/model/ChamberTest.java
  src/test/java/WebsocketServer/game/model/FloorTest.java
  src/test/java/WebsocketServer/services/GameBoardManagerTest.java
  src/test/java/WebsocketServer/services/user/CreateUserServiceTest.java
Labels: enhancement

#78 77 as a user i want to start the game
  src/main/java/WebsocketServer/game/model/Game.java
  src/main/java/WebsocketServer/services/GameBoardManager.java
  src/main/java/WebsocketServer/services/GameService.java
  src/main/java/WebsocketServer/services/LobbyService.java
  src/main/java/WebsocketServer/services/json/ActionValues.java
  src/main/java/WebsocketServer/services/user/CreateUserService.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
  src/test/java/WebsocketServer/game/model/GameTest.java
  src/test/java/WebsocketServer/services/LobbyServiceTests.java
  src/test/java/WebsocketServer/services/user/CreateUserServiceTest.java
Labels: enhancement

#80 Lobby view
  src/main/java/WebsocketServer/game/lobby/Lobby.java
  src/main/java/WebsocketServer/services/LobbyService.java
  src/main/java/WebsocketServer/services/SendMessageService.java
  src/main/java/WebsocketServer/services/json/ActionValues.java
  src/main/java/WebsocketServer/services/user/ManageUserService.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
  src/test/java/WebsocketServer/game/lobby/LobbyTest.java
  src/test/java/WebsocketServer/services/LobbyServiceTests.java
  src/test/java/WebsocketServer/services/user/ManageUserServiceTest.java
Labels: enhancement

#71 58 implement card communication between server and client
  src/main/java/WebsocketServer/game/model/CardCombination.java
  src/main/java/WebsocketServer/game/model/Game.java
  src/main/java/WebsocketServer/game/model/Player.java
  src/main/java/WebsocketServer/game/model/PlayingCard.java
  src/main/java/WebsocketServer/game/services/CardController.java
  src/main/java/WebsocketServer/game/services/GameBoardService.java
  src/main/java/WebsocketServer/services/CardManager.java
  src/main/java/WebsocketServer/services/GameService.java
  src/main/java/WebsocketServer/services/LobbyService.java
  src/test/java/WebsocketServer/game/model/GameTest.java
  src/test/java/WebsocketServer/game/model/PlayingCardTest.java
  src/test/java/WebsocketServer/game/services/CardControllerTest.java
  src/test/java/WebsocketServer/services/CardManagerTest.java
  src/test/java/WebsocketServer/services/LobbyServiceTests.java
Labels: enhancement

#90 49 update readmemd
  README.md
  src/main/java/WebsocketServer/messaging/dtos/OutputMessage.java
Labels: documentation, enhancement

#92 Mission cards feature
  src/main/java/WebsocketServer/game/model/Game.java
  src/main/java/WebsocketServer/game/model/GameBoard.java
  src/main/java/WebsocketServer/game/model/MissionCard.java
  src/main/java/WebsocketServer/services/GameService.java
  src/test/java/WebsocketServer/game/model/MissionCardTest.java
Labels: enhancement

#84 83 gameboard communication rework
  src/main/java/WebsocketServer/game/model/Chamber.java
  src/main/java/WebsocketServer/game/model/Field.java
  src/main/java/WebsocketServer/game/model/FieldUpdateMessage.java
  src/main/java/WebsocketServer/game/model/Floor.java
  src/main/java/WebsocketServer/game/model/Game.java
  src/main/java/WebsocketServer/game/model/GameBoard.java
  src/main/java/WebsocketServer/services/GameBoardManager.java
  src/main/java/WebsocketServer/services/GameService.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
  src/test/java/WebsocketServer/game/model/FieldTest.java
  src/test/java/WebsocketServer/game/model/FloorTest.java
  src/test/java/WebsocketServer/game/model/GameTest.java
  src/test/java/WebsocketServer/services/GameBoardManagerTest.java
  src/test/java/WebsocketServer/services/GameServiceTest.java
Labels: enhancement

#96 Tests for coverage
  src/main/java/websocketserver/game/model/GameBoard.java
  src/test/java/websocketserver/game/model/GameBoardTest.java
Labels: bug
