Repository SE2-Projekt-WelcomeToTheMoon/server, pull requests merged in 2024-06, with the labels that each got.

#108 97 as a user i want to continue the game after a short disconnect
  README.md
  src/main/java/websocketserver/services/json/ActionValues.java
  src/main/java/websocketserver/services/user/CreateUserService.java
  src/main/java/websocketserver/websocket/handler/WebSocketHandlerImpl.java
Labels: enhancement

#112 Winning screen
  src/main/java/websocketserver/services/LobbyService.java
  src/main/java/websocketserver/services/json/ActionValues.java
  src/main/java/websocketserver/websocket/handler/WebSocketHandlerImpl.java
  src/test/java/websocketserver/services/LobbyServiceTests.java
Labels: enhancement

#115 114 improve code
  src/main/java/websocketserver/game/enums/ChosenCardCombination.java
  src/main/java/websocketserver/game/model/CardCombination.java
  src/main/java/websocketserver/game/model/Chamber.java
  src/main/java/websocketserver/game/model/PlayingCard.java
  src/main/java/websocketserver/game/services/CardController.java
  src/main/java/websocketserver/game/services/GameBoardService.java
  src/test/java/websocketserver/game/model/ChamberTest.java
  src/test/java/websocketserver/game/model/FloorTest.java
  src/test/java/websocketserver/game/model/GameBoardTest.java
Labels: bug

#117 Winning screen
  src/main/java/websocketserver/services/GameService.java
  src/main/java/websocketserver/services/LobbyService.java
  src/main/java/websocketserver/websocket/handler/WebSocketHandlerImpl.java
  src/test/java/websocketserver/services/GameServiceTest.java
Labels: enhancement

#123 System error
  src/main/java/websocketserver/game/model/GameBoard.java
  src/main/java/websocketserver/services/GameService.java
  src/test/java/websocketserver/services/GameServiceTest.java
Labels: enhancement

#125 124 fix issues with checking corrext move
  src/main/java/websocketserver/game/model/Floor.java
  src/main/java/websocketserver/game/model/Game.java
  src/test/java/websocketserver/game/model/FloorTest.java
  src/test/java/websocketserver/game/model/GameTest.java
Labels: bug

#111 109 as a user i do not want to host the game logic on my own
  .github/workflows/build_and_push_dc_image.yml
  Dockerfile
  src/main/java/websocketserver/game/model/Game.java
  src/main/java/websocketserver/services/CardManager.java
  src/main/java/websocketserver/services/GameBoardManager.java
  src/main/java/websocketserver/services/GameService.java
  src/main/java/websocketserver/services/LobbyService.java
  src/main/java/websocketserver/services/json/GenerateJSONObjectService.java
  src/main/java/websocketserver/services/user/CreateUserService.java
  src/main/java/websocketserver/services/user/ManageUserService.java
  src/main/java/websocketserver/websocket/handler/WebSocketHandlerImpl.java
  src/test/java/websocketserver/services/GenerateJSONObjectServiceTest.java
  src/test/java/websocketserver/services/LobbyServiceTests.java
Labels: enhancement

#128 127 rework reward structure
  src/main/java/websocketserver/game/enums/RewardCategory.java
  src/main/java/websocketserver/game/model/Reward.java
  src/main/java/websocketserver/game/services/GameBoardService.java
  src/test/java/websocketserver/game/model/ChamberTest.java
  src/test/java/websocketserver/game/model/FloorTest.java
  src/test/java/websocketserver/game/model/GameBoardTest.java
  src/test/java/websocketserver/game/model/RewardTest.java
  src/test/java/websocketserver/game/services/GameBoardServiceTest.java
Labels: enhancement

#130 Fix sonarcloud high issues
  src/main/java/websocketserver/game/model/Floor.java
  src/main/java/websocketserver/game/model/Game.java
  src/main/java/websocketserver/websocket/handler/WebSocketHandlerImpl.java
Labels: documentation

#126 99 as a user i want to see room rewards locally and get rewards distributed when finishing a chamber
  src/main/java/websocketserver/game/model/Chamber.java
  src/main/java/websocketserver/game/model/Game.java
  src/main/java/websocketserver/game/services/GameBoardService.java
  src/main/java/websocketserver/services/GameBoardManager.java
  src/main/java/websocketserver/services/GameService.java
  src/test/java/websocketserver/game/model/ChamberTest.java
  src/test/java/websocketserver/game/model/GameTest.java
  src/test/java/websocketserver/game/services/GameBoardServiceTest.java
  src/test/java/websocketserver/services/GameBoardManagerTest.java
  src/test/java/websocketserver/services/GameServiceTest.java
Labels: enhancement

#132 Fix sonarcloud high issues
  src/main/java/websocketserver/websocket/handler/WebSocketHandlerImpl.java
Labels: documentation

#133 Missing tests mission cards
  .github/workflows/build_and_push_dc_image.yml
  Dockerfile
  src/main/java/websocketserver/game/enums/MissionType.java
  src/main/java/websocketserver/game/model/Game.java
  src/main/java/websocketserver/game/model/GameBoard.java
  src/main/java/websocketserver/game/model/MissionCard.java
  src/main/java/websocketserver/services/GameBoardManager.java
  src/main/java/websocketserver/services/GameService.java
  src/main/java/websocketserver/websocket/handler/WebSocketHandlerImpl.java
  src/test/java/websocketserver/game/model/GameBoardTest.java
  src/test/java/websocketserver/game/model/GameTest.java
  src/test/java/websocketserver/game/model/MissionCardTest.java
  src/test/java/websocketserver/services/GameBoardManagerTest.java
  src/test/java/websocketserver/services/GameServiceTest.java
Labels: bug, enhancement
