Repository SE2-Projekt-WelcomeToTheMoon/server, pull requests merged in 2024-04, with the labels that each got.

#14 new setup for server structure
  src/main/java/WebsocketServer/websocket/broker/WebSocketBrokerConfig.java
  src/main/java/WebsocketServer/websocket/broker/WebSocketBrokerController.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
  src/test/java/WebsocketServer/WebSocketBrokerIntegrationTest.java
Labels: enhancement

#20 19 finalize gameboard
  src/main/java/WebsocketServer/game/enums/FieldValue.java
  src/main/java/WebsocketServer/game/exceptions/FinalizedException.java
  src/main/java/WebsocketServer/game/model/Chamber.java
  src/main/java/WebsocketServer/game/model/Field.java
  src/main/java/WebsocketServer/game/model/Floor.java
  src/main/java/WebsocketServer/game/model/GameBoard.java
  src/main/java/WebsocketServer/game/services/GameBoardService.java
  src/test/java/WebsocketServer/game/model/ChamberTest.java
  src/test/java/WebsocketServer/game/model/FieldTest.java
  src/test/java/WebsocketServer/game/model/FloorTest.java
  src/test/java/WebsocketServer/game/model/GameBoardTest.java
  src/test/java/WebsocketServer/game/services/GameBoardServiceTest.java
Labels: enhancement

#21 Lobby
  src/main/java/WebsocketServer/game/lobby/Lobby.java
  src/main/java/WebsocketServer/messaging/dtos/StompMessage.java
  src/main/java/WebsocketServer/services/LobbyService.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
  src/test/java/WebsocketServer/WebSocketHandlerIntegrationTest.java
  src/test/java/WebsocketServer/game/lobby/LobbyTest.java
Labels: enhancement

#23 changed server-path to welcome-to-the-moon(same as the app)
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerConfig.java
  src/test/java/WebsocketServer/WebSocketHandlerIntegrationTest.java
Labels: enhancement

#27 Created new method in UserClientService.java class for user registrat…
  src/main/java/WebsocketServer/services/UserClientService.java
Labels: enhancement

#25 Created GenerateJSONObjectService.java class to generate generic JSON…
  src/main/java/WebsocketServer/services/GenerateJSONObjectService.java
  src/main/java/WebsocketServer/services/LobbyService.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
Labels: enhancement

#31 dapting UserClientService
  src/main/java/WebsocketServer/services/GenerateJSONObjectService.java
  src/main/java/WebsocketServer/services/UserClientService.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
Labels: enhancement

#33 32 revert to last commit
  src/main/java/WebsocketServer/game/lobby/Lobby.java
  src/main/java/WebsocketServer/services/GenerateJSONObjectService.java
  src/main/java/WebsocketServer/services/LobbyService.java
  src/main/java/WebsocketServer/services/UserClientService.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
  src/test/java/WebsocketServer/WebSocketHandlerIntegrationTest.java
Labels: bug

#34 minor issues
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
  src/test/java/WebsocketServer/WebSocketHandlerIntegrationTest.java
Labels: bug

#36 small changes
  src/main/java/WebsocketServer/game/lobby/Lobby.java
  src/main/java/WebsocketServer/services/GenerateJSONObjectService.java
  src/main/java/WebsocketServer/services/LobbyService.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
  src/test/java/WebsocketServer/WebSocketHandlerIntegrationTest.java
Labels: documentation

#39 37 add card structures
  src/main/java/WebsocketServer/game/model/CardCombination.java
  src/main/java/WebsocketServer/game/model/CardStack.java
  src/main/java/WebsocketServer/game/model/PlayingCard.java
  src/main/java/WebsocketServer/game/services/CardController.java
  src/test/java/WebsocketServer/game/model/CardCombinationTest.java
  src/test/java/WebsocketServer/game/model/CardStackTest.java
  src/test/java/WebsocketServer/game/model/PlayingCardTest.java
  src/test/java/WebsocketServer/game/services/CardControllerTest.java
Labels: enhancement

#45 Reimplemented userclient code
  src/main/java/WebsocketServer/services/LobbyService.java
  src/main/java/WebsocketServer/services/UserClientService.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerConfig.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
Labels: bug, documentation, enhancement

#48 LOG Ausgabe von System.out.println durch LOGGER ersetzt.
  src/main/java/WebsocketServer/services/LobbyService.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
Labels: documentation

#53 30 adapting userclientservice
  pom.xml
  src/main/java/WebsocketServer/services/UserClientService.java
  src/main/java/WebsocketServer/services/user/CreateUserService.java
  src/main/java/WebsocketServer/services/user/ManageUserService.java
  src/main/java/WebsocketServer/services/user/UserListService.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
  src/test/java/WebsocketServer/services/GenerateJSONObjectServiceTest.java
  src/test/java/WebsocketServer/services/user/CreateUserServiceTest.java
  src/test/java/WebsocketServer/services/user/ManageUserServiceTest.java
Labels: documentation, enhancement, testing

#54 52 create room completion reward structure
  src/main/java/WebsocketServer/game/enums/RewardCategory.java
  src/main/java/WebsocketServer/game/model/Chamber.java
  src/main/java/WebsocketServer/game/model/Floor.java
  src/main/java/WebsocketServer/game/model/Reward.java
  src/main/java/WebsocketServer/game/services/GameBoardService.java
  src/test/java/WebsocketServer/game/model/CardStackTest.java
  src/test/java/WebsocketServer/game/model/ChamberTest.java
  src/test/java/WebsocketServer/game/model/FieldTest.java
  src/test/java/WebsocketServer/game/model/FloorTest.java
  src/test/java/WebsocketServer/game/model/GameBoardTest.java
  src/test/java/WebsocketServer/game/model/PlayingCardTest.java
  src/test/java/WebsocketServer/game/model/RewardTest.java
Labels: enhancement

#50 18 create data model for game
  src/main/java/WebsocketServer/game/enums/ChoosenCardCombination.java
  src/main/java/WebsocketServer/game/enums/GameState.java
  src/main/java/WebsocketServer/game/exceptions/GameStateException.java
  src/main/java/WebsocketServer/game/lobby/Lobby.java
  src/main/java/WebsocketServer/game/model/Game.java
  src/main/java/WebsocketServer/game/model/Player.java
  src/main/java/WebsocketServer/game/services/CardController.java
  src/test/java/WebsocketServer/game/model/GameTest.java
  src/test/java/WebsocketServer/game/model/PlayerTest.java
Labels: enhancement

#57 Initial data structure
  src/main/java/WebsocketServer/game/model/GameBoard.java
  src/main/java/WebsocketServer/game/model/SystemErrors.java
  src/test/java/WebsocketServer/game/model/GameBoardTest.java
  src/test/java/WebsocketServer/game/model/SystemErrorsTest.java
Labels: enhancement

#62 61 implement logic that user is beeind removed if connection is disconnected
  src/main/java/WebsocketServer/services/user/CreateUserService.java
  src/main/java/WebsocketServer/services/user/ManageUserService.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
  src/test/java/WebsocketServer/services/user/CreateUserServiceTest.java
  src/test/java/WebsocketServer/services/user/ManageUserServiceTest.java
Labels: enhancement

#64 Added new attribute WebSocketSession to user object.
  src/main/java/WebsocketServer/services/user/CreateUserService.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
  src/test/java/WebsocketServer/services/user/CreateUserServiceTest.java
Labels: enhancement

#70 Lobby after disconnection
  src/main/java/WebsocketServer/game/lobby/Lobby.java
  src/main/java/WebsocketServer/services/LobbyService.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
  src/test/java/WebsocketServer/WebSocketHandlerIntegrationTest.java
  src/test/java/WebsocketServer/game/lobby/LobbyTest.java
  src/test/java/WebsocketServer/services/LobbyServiceTests.java
Labels: enhancement

#72 small changes
  src/main/java/WebsocketServer/services/LobbyService.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
Labels: documentation

#73 66 enhance error handling for user creation
  pom.xml
  src/main/java/WebsocketServer/services/LobbyService.java
  src/main/java/WebsocketServer/services/SendMessageService.java
  src/main/java/WebsocketServer/services/json/ActionValues.java
  src/main/java/WebsocketServer/services/json/GenerateJSONObjectService.java
  src/main/java/WebsocketServer/services/user/CreateUserService.java
  src/main/java/WebsocketServer/services/user/ManageUserService.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
  src/test/java/WebsocketServer/services/GenerateJSONObjectServiceTest.java
  src/test/java/WebsocketServer/services/LobbyServiceTests.java
  src/test/java/WebsocketServer/services/user/CreateUserServiceTest.java
  src/test/java/WebsocketServer/services/user/ManageUserServiceTest.java
Labels: enhancement

#74 Lobby user interaction
  src/main/java/WebsocketServer/game/lobby/Lobby.java
  src/main/java/WebsocketServer/services/LobbyService.java
  src/main/java/WebsocketServer/services/SendMessageService.java
  src/main/java/WebsocketServer/websocket/handler/WebSocketHandlerImpl.java
  src/test/java/WebsocketServer/game/lobby/LobbyTest.java
  src/test/java/WebsocketServer/services/LobbyServiceTests.java
Labels: documentation
